# Generated by Django 3.2.4 on 2021-06-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='kategoriya nomi')),
            ],
        ),
        migrations.CreateModel(
            name='NewTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='yanglikning nomi')),
                ('time', models.DateTimeField(verbose_name='vaxti')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='rasm')),
                ('description', models.TextField(max_length=10000, verbose_name='opisanie')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.category')),
            ],
        ),
    ]
