# Generated by Django 3.2.4 on 2021-06-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtopic',
            name='author',
            field=models.CharField(max_length=50, null=True, verbose_name='avtor'),
        ),
    ]
